import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import {getFirestore,doc,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const M=window.DEMOL_QUESTIONS,O=window.DEMOL_OPEN_QUESTIONS,N=window.DEMOL_NAMES,$=id=>document.getElementById(id);
N.forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;$('name').appendChild(o)});
// Open vragen worden tussen de meerkeuzevragen gemengd zodat Mol-vragen niet bij elkaar staan.
const slots=[3,7,11,15,19,23,27,31,35,40]; let sequence=[],mi=0,oi=0;
for(let pos=1;pos<=40;pos++){if(slots.includes(pos))sequence.push({type:'open',i:oi++});else sequence.push({type:'mc',i:mi++})}
let idx=0,person='',mc=Array(M.length).fill(null),open=Array(O.length).fill(''),photoFile=null,appFirebase=null,db=null,storage=null;
function show(id){['start','quiz','review','done'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
$('photo').addEventListener('change',e=>{photoFile=e.target.files[0]||null;if(photoFile){$('preview').src=URL.createObjectURL(photoFile);$('preview').style.display='block'}else $('preview').style.display='none'});
function questionText(item){let t=O[item.i];if(item.type==='open'&&item.i===5){const mol=open[1].trim();t=t.replace('{mol}',mol||'die persoon')}return t}
function saveOpen(){const item=sequence[idx];if(item.type==='open')open[item.i]=$('openAnswer').value.trim()}
function render(){const item=sequence[idx];$('who').textContent=person;$('counter').textContent=(idx+1)+' / 40';$('bar').style.width=((idx+1)/40*100)+'%';$('qno').textContent=(item.type==='mc'?'Meerkeuzevraag ':'Open vraag ')+(item.i+1);$('options').innerHTML='';$('openAnswer').classList.add('hidden');if(item.type==='mc'){const q=M[item.i];$('question').textContent=q.vraag;['A','B','C','D'].forEach(l=>{const lab=document.createElement('label');lab.className='option'+(mc[item.i]===l?' selected':'');lab.innerHTML='<input type="radio" name="ans" value="'+l+'" '+(mc[item.i]===l?'checked':'')+'><span class="letter">'+l+'</span><span>'+q[l]+'</span>';lab.querySelector('input').onchange=()=>{mc[item.i]=l;render()};$('options').appendChild(lab)})}else{$('question').textContent=questionText(item);$('openAnswer').classList.remove('hidden');$('openAnswer').value=open[item.i]||''}$('prev').disabled=idx===0;$('next').textContent=idx===39?'Naar controle →':'Volgende →';$('quizMsg').classList.add('hidden')}
$('startBtn').onclick=()=>{person=$('name').value;photoFile=$('photo').files[0]||null;if(!person||!photoFile){$('startMsg').textContent=!person?'Kies eerst je naam.':'Upload eerst een foto van jezelf.';$('startMsg').classList.remove('hidden');return}if(!photoFile.type.startsWith('image/')){ $('startMsg').textContent='Kies een geldig afbeeldingsbestand.';$('startMsg').classList.remove('hidden');return}if(photoFile.size>8*1024*1024){$('startMsg').textContent='De foto is te groot. Kies een foto kleiner dan 8 MB.';$('startMsg').classList.remove('hidden');return}$('startMsg').classList.add('hidden');show('quiz');render()};
$('prev').onclick=()=>{saveOpen();if(idx>0){idx--;render()}};
$('next').onclick=()=>{const item=sequence[idx];if(item.type==='open'){saveOpen();if(!open[item.i]){$('quizMsg').textContent='Vul eerst een antwoord in.';$('quizMsg').classList.remove('hidden');return}}else if(!mc[item.i]){$('quizMsg').textContent='Kies eerst een antwoord.';$('quizMsg').classList.remove('hidden');return}if(idx<39){idx++;render()}else{$('reviewText').textContent='Alle 30 meerkeuzevragen en 10 open vragen zijn ingevuld voor '+person+'.';show('review')}};
$('backBtn').onclick=()=>{show('quiz');render()};